# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: im_helpers 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "im_helpers"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["julbouln"]
  s.date = "2017-02-20"
  s.description = "immat\u{e9}riel.fr helpers lib"
  s.email = "jboulnois@immateriel.fr"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/im_helpers.rb",
    "lib/im_helpers/ext/date.rb",
    "lib/im_helpers/ext/fileutils.rb",
    "lib/im_helpers/ext/helpers/date_helpers.rb",
    "lib/im_helpers/ext/helpers/number_helpers.rb",
    "lib/im_helpers/ext/helpers/string_helpers.rb",
    "lib/im_helpers/ext/i18n.rb",
    "lib/im_helpers/ext/number.rb",
    "lib/im_helpers/ext/string.rb",
    "lib/im_helpers/forex.rb",
    "lib/im_helpers/ip_to_country.rb",
    "lib/im_helpers/language.rb",
    "lib/im_helpers/name_extractor.rb",
    "lib/im_helpers/territories.rb"
  ]
  s.homepage = "http://github.com/immateriel/im_helpers"
  s.rubygems_version = "2.4.8"
  s.summary = "immat\u{e9}riel.fr helpers lib"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<iso-639>, ["~> 0.2.0"])
      s.add_runtime_dependency(%q<countries>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<currencies>, ["~> 0.4.0"])
      s.add_runtime_dependency(%q<htmlentities>, ["~> 4.3.0"])
      s.add_runtime_dependency(%q<html_truncator>, ["~> 0.4.0"])
      s.add_runtime_dependency(%q<unidecoder>, [">= 0"])
      s.add_runtime_dependency(%q<unicode>, ["~> 0.4.0"])
      s.add_runtime_dependency(%q<levenshtein-ffi>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2.0"])
      s.add_runtime_dependency(%q<i18n>, ["~> 0.7.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<iso-639>, ["~> 0.2.0"])
      s.add_dependency(%q<countries>, ["~> 1.2.0"])
      s.add_dependency(%q<currencies>, ["~> 0.4.0"])
      s.add_dependency(%q<htmlentities>, ["~> 4.3.0"])
      s.add_dependency(%q<html_truncator>, ["~> 0.4.0"])
      s.add_dependency(%q<unidecoder>, [">= 0"])
      s.add_dependency(%q<unicode>, ["~> 0.4.0"])
      s.add_dependency(%q<levenshtein-ffi>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["~> 3.2.0"])
      s.add_dependency(%q<i18n>, ["~> 0.7.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<iso-639>, ["~> 0.2.0"])
    s.add_dependency(%q<countries>, ["~> 1.2.0"])
    s.add_dependency(%q<currencies>, ["~> 0.4.0"])
    s.add_dependency(%q<htmlentities>, ["~> 4.3.0"])
    s.add_dependency(%q<html_truncator>, ["~> 0.4.0"])
    s.add_dependency(%q<unidecoder>, [">= 0"])
    s.add_dependency(%q<unicode>, ["~> 0.4.0"])
    s.add_dependency(%q<levenshtein-ffi>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["~> 3.2.0"])
    s.add_dependency(%q<i18n>, ["~> 0.7.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

