# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: im_helpers 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "im_helpers"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["julbouln"]
  s.date = "2014-10-08"
  s.description = "immat\u{e9}riel.fr helpers lib"
  s.email = "jboulnois@immateriel.fr"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/date_helpers.rb",
    "lib/i18n_helpers.rb",
    "lib/ip_to_country.rb",
    "lib/language.rb",
    "lib/number_helpers.rb",
    "lib/string_helpers.rb",
    "lib/territories.rb"
  ]
  s.homepage = "http://github.com/immateriel/im_helpers"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "immat\u{e9}riel.fr helpers lib"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<htmlentities>, [">= 0"])
      s.add_runtime_dependency(%q<html_truncator>, [">= 0"])
      s.add_runtime_dependency(%q<iso-639>, [">= 0"])
      s.add_runtime_dependency(%q<countries>, [">= 0"])
      s.add_runtime_dependency(%q<currencies>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<htmlentities>, [">= 0"])
      s.add_dependency(%q<html_truncator>, [">= 0"])
      s.add_dependency(%q<iso-639>, [">= 0"])
      s.add_dependency(%q<countries>, [">= 0"])
      s.add_dependency(%q<currencies>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<htmlentities>, [">= 0"])
    s.add_dependency(%q<html_truncator>, [">= 0"])
    s.add_dependency(%q<iso-639>, [">= 0"])
    s.add_dependency(%q<countries>, [">= 0"])
    s.add_dependency(%q<currencies>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

